### PR TITLE
trajectory_tracker_msgs: fix header install directory

### LINKED ISSUE #11: Install directory of trajectory_tracker_msgs header is wrong
https://github.com/at-wat/neonavigation_msgs/blob/7c7f4e134ddaf17f8e6dadc730fcc3d7731e25f7/trajectory_tracker_msgs/CMakeLists.txt#L64-L66
this installs header under `include/trajectory_tracker_msgs/trajectory_tracker_msgs/`

### PR DESCRIPTION
**Pull request by at-wat**
fix #11

### CODE REVIEW

**Comment by at-wat** [comment]
## [#30] PASSED on melodic

<details><summary>All tests passed</summary>


```
build/test_results/trajectory_tracker_msgs/gtest-test_convert.xml: 2 tests
build/test_results/trajectory_tracker_msgs/roslint-trajectory_tracker_msgs.xml: 1 tests
Summary: 3 tests, 0 errors, 0 failures, 0 skipped
```
</details>

**Comment by at-wat** [comment]
master:
```
-- Installing: /opt/ros/kinetic/include/trajectory_tracker_msgs/trajectory_tracker_msgs
-- Installing: /opt/ros/kinetic/include/trajectory_tracker_msgs/trajectory_tracker_msgs/converter.h
```

this:
```
-- Up-to-date: /opt/ros/kinetic/include/trajectory_tracker_msgs
-- Up-to-date: /opt/ros/kinetic/include/trajectory_tracker_msgs/converter.h
```

**Comment by at-wat** [comment]
@ykoga-kyutech please try this branch

**Comment by ykoga-kyutech** [comment]
Thx, I try it soon.

**Comment by ykoga-kyutech** [comment]
@at-wat The build passed. LGTM

**Pull request merged**
